name: chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.7.0
  firebase_database: ^11.0.4
  google_sign_in: ^6.1.6
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#0B0B0B"
  image: assets/splash_image.png
  web: true

  ios: false
  macos: false

  android_12:
    color: "#0B0B0B"
    image: assets/splash_image.png

flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
    - assets/login_bg.png
    - assets/chat_bg.png
    - assets/menu_bg.png


